# config/packages/easy_admin.yaml
easy_admin:
  site_name: 'TUTO-DECO'
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      # the following Twig template can be located anywhere in the application.
      # it can also be added to the twig.form_themes option to use it in the
      # entire application, not only the backend
      # - 'admin/form.html.twig'
  user:
    display_name: true
    display_avatar: false
  entities:
    Tutorial :
      class: App\Entity\Tutorial
      list:
        actions: ['-new']
        fields:
          - { property: 'imageName', type: 'image', base_path: '/uploads/tutorials' }
          - title
          - description
          - validation
          - createdAt
      edit:
        fields:
          - { type: 'tab', label: 'Informations'}
          - title
          - description
          - { property: 'imageFile', type: 'vich_image' }
          - {type: 'tab', label: 'étapes'}
          - {property: 'steps', label: 'étapes', type: 'collection', type_options: {entry_type: 'App\Form\StepType', by_reference: false}}

    User :
      class: App\Entity\User
      list:
        actions: ['-new']
        fields:
          - lastName
          - firstName
          - nickname
          - roles
          - { property: 'pictureName', type: 'image', base_path: '/uploads/users' }
      edit:
        fields:
          - {property: 'lastname', type: 'text'}
          - {property: 'firstname', type: 'text'}
          - nickname
          - { property: 'roles', type: 'choice', type_options: {mapped: true, expanded: true, multiple: true, choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' }}}
          - { property: 'imageFile', type: 'vich_image' }
    Material :
      class: App\Entity\Material
      list:
        fields:
          - label
          - unit
      form:
        fields:
          - label
          - unit
    Tool :
      class: App\Entity\Tool
      list:
        fields:
          - label
          - unit
      form:
        fields:
          - label
          - unit
    Comment :
      class: App\Entity\Comment
      list:
        actions: ['-new', '-edit', 'show']
        fields:
          - content
          - user
          - tutorial
          - createdAt
      show:
        actions: ['-edit']
        fields:
          - content
          - user
          - tutorial
          - createdAt
          - { property: 'picture', type: 'image', base_path: '/uploads/comments' }

    # change the following to the namespaces of your own entities
    #- App\Entity\Tag
    #-
    #-
