# config/packages/easy_admin.yaml
easy_admin:
  entities:
    # change the following to the namespaces of your own entities
    - App\Entity\Tutorial
    - App\Entity\Tag
    - App\Entity\User
    - App\Entity\Material
    - App\Entity\Tool
